version: 3

project:
  locator: SolaceLabs_solace-intellij-plugin
  id: SolaceLabs_solace-intellij-plugin
  name: solace-intellij-plugin
  teams: []
  labels:
    - java

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"

paths:
  exclude:
    - ./.git
    - ./.github

telemetry:
  scope: full
